name: build and deploy base images

on:
  push:
    branches:
    - "main"

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      java7: ${{ steps.changes.outputs.java7 }}
      java8: ${{ steps.changes.outputs.java8 }}
      readme: ${{ steps.changes.outputs.readme }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            java7:
            - 'Dockerfile.java7'
            java8:
            - 'Dockerfile.java8'
            readme:
            - 'readme.md'
  build_java7:
    needs: changes
    if: ${{ needs.changes.outputs.java7 == 'true' }}
    name: Build java7 docker image
    runs-on: ubuntu-latest
    steps:
     - name: Check out code
       uses: actions/checkout@v3
       with:
        lfs: true
     - name: Log in to Docker Hub
       uses: docker/login-action@v2
       with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
     - name: Build and push
       uses: docker/build-push-action@v4
       with:
        context: .
        platforms: linux/amd64
        file: "Dockerfile.java7"
        push: true
        tags: vtarahan/netapp:java7
        provenance: false
  build_java8:
    needs: changes
    if: ${{ needs.changes.outputs.java8 == 'true' }}
    name: Build java8 docker image
    runs-on: ubuntu-latest
    steps:
     - name: Check out code
       uses: actions/checkout@v3
       with:
        lfs: true
     - name: Log in to Docker Hub
       uses: docker/login-action@v2
       with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
     - name: Build and push
       uses: docker/build-push-action@v4
       with:
        context: .
        platforms: linux/amd64
        file: "Dockerfile.java8"
        push: true
        tags: vtarahan/netapp:java8
        provenance: false
  docker_hub_description:
    needs: changes
    if: ${{ needs.changes.outputs.readme == 'true' }}
    name: Docker Hub description update
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: vtarahan/netapp